# Build the Go Binary.
FROM golang:1.26 AS build_auth
ENV CGO_ENABLED=0
ENV GOPROXY=https://proxy.golang.org|direct
ARG BUILD_TAG

# Copy module files first so dependency downloads are cached independently from
# source changes.
COPY go.mod go.sum /service/
WORKDIR /service
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

# Copy the source code into the container.
COPY . /service

# Build the service binary. We are doing this last since this will be different
# every time we run through this process.
WORKDIR /service/api/services/auth
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -ldflags "-X main.tag=${BUILD_TAG}"


# Run the Go Binary in Alpine.
FROM alpine:3.23
ARG BUILD_DATE
ARG BUILD_TAG
RUN addgroup -g 1000 -S auth && \
    adduser -u 1000 -h /service -G auth -S auth
COPY --from=build_auth --chown=auth:auth /service/zarf/keys/. /service/zarf/keys/.
COPY --from=build_auth --chown=auth:auth /service/api/services/auth/auth /service/auth
WORKDIR /service
USER auth
CMD ["./auth"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="auth" \
      org.opencontainers.image.authors="William Kennedy <bill@ardanlabs.com>" \
      org.opencontainers.image.source="https://github.com/ardanlabs/service/tree/master/a/services/auth" \
      org.opencontainers.image.revision="${BUILD_TAG}" \
      org.opencontainers.image.vendor="Ardan Labs"
