# Build the Go Binary.
FROM golang:1.26 AS build_schoolcrm
ENV CGO_ENABLED=0
ARG BUILD_TAG

# Create the service directory and the copy the module files first and then
# download the dependencies. If this doesn't change, we won't need to do this
# again in future builds.
# RUN mkdir /service
# COPY go.* /service/
# WORKDIR /service
# RUN go mod download

# Copy the source code into the container.
COPY . /service

# Build the admin binary.
WORKDIR /service/api/tooling/admin
RUN go build -ldflags "-X main.tag=${BUILD_TAG}"

# Build the service binary.
WORKDIR /service/api/services/schoolcrm
RUN go build -ldflags "-X main.tag=${BUILD_TAG}"


# Run the Go Binary in Alpine.
FROM alpine:3.23
ARG BUILD_DATE
ARG BUILD_TAG
RUN addgroup -g 1000 -S schoolcrm && \
    adduser -u 1000 -h /service -G schoolcrm -S schoolcrm
COPY --from=build_schoolcrm --chown=schoolcrm:schoolcrm /service/api/tooling/admin/admin /service/admin
COPY --from=build_schoolcrm --chown=schoolcrm:schoolcrm /service/api/services/schoolcrm/schoolcrm /service/schoolcrm
WORKDIR /service
USER schoolcrm
CMD ["./schoolcrm"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="schoolcrm-api" \
      org.opencontainers.image.source="https://github.com/owezzy/schoolCRM/tree/main/api/services/schoolcrm" \
      org.opencontainers.image.revision="${BUILD_TAG}" \
      org.opencontainers.image.vendor="SchoolCRM"
