apiVersion: v1
kind: Service
metadata:
  name: schoolcrm-service
  namespace: schoolcrm-system

spec:
  type: ClusterIP

  ports:
    - name: schoolcrm
      port: 3000
      targetPort: schoolcrm
    - name: schoolcrm-debug
      port: 3010
      targetPort: schoolcrm-debug
    - name: metrics
      port: 4000
      targetPort: metrics
    - name: metrics-debug
      port: 4010
      targetPort: metrics-debug
    - name: prometheus
      port: 4020
      targetPort: metrics-prom
