[build]
builder = "DOCKERFILE"
dockerfilePath = "zarf/docker/dockerfile.auth"

[deploy]
healthcheckPath = "/v1/readiness"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
