apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/web-admin/
  - ./dev-web-admin-configmap.yaml
patches:
  - path: ./dev-web-admin-patch-deploy.yaml
  - path: ./dev-web-admin-patch-service.yaml
images:
  - name: web-admin-image
    newName: localhost/schoolcrm/web-admin
    newTag: 0.0.1
