apiVersion: v1
kind: Service
metadata:
  name: schoolcrm-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "schoolcrm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "schoolcrm.selectorLabels" . | nindent 4 }}
  ports:
    - name: schoolcrm
      port: {{ .Values.service.ports.http }}
      targetPort: schoolcrm
    - name: schoolcrm-debug
      port: {{ .Values.service.ports.debug }}
      targetPort: schoolcrm-debug
    - name: metrics
      port: {{ .Values.service.ports.metricsHttp }}
      targetPort: metrics
    - name: metrics-debug
      port: {{ .Values.service.ports.metricsDebug }}
      targetPort: metrics-debug
    - name: prometheus
      port: {{ .Values.service.ports.metricsPrometheus }}
      targetPort: metrics-prom
